name: CI
on:
  push:
    branches: [release-1.2.0]
  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: currencyconverter.flatpak
          manifest-path: io.github.idevecore.CurrencyConverter.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: true

